platformName: Android
platformVersion: 7.1.2
deviceName: 127.0.0.1:62001
appPackage: com.tal.kaoyan
appActivity: com.tal.kaoyan.ui.activity.ucenter.LoginActivity
noReset: True
ip: '127.0.0.1'
port: '4723'